apiVersion: v1
kind: Service
metadata:
  name: humetric-api
spec:
  selector:
    app: humetric
    component: api
  ports:
    - port: 8002
      targetPort: 8002
      protocol: TCP
  type: ClusterIP
